### ISSUE TITLE
initial value via 'selection' does not work

### ISSUE THREAD

**Issue by ssendev** [aupac/ember-aupac-typeahead#1]
this can be seen in the demo

**Comment by jackmatt2** [comment]
oh yeah, I must have broken it.  Will get this fixed tonight.

**Comment by jackmatt2** [comment]
@ssendev fixed as of version 0.0.6

**Comment by jackmatt2** [comment]
@ssendev you might want to install 0.0.9, that will install the bower dependency properly.

**Comment by ssendev** [comment]
cool that was fast. it is working now. i have made a small enhancement #2 but am not entirely sure it is bulletproof
