### ISSUE TITLE
Allow free input

### ISSUE THREAD

**Issue by ymph** [aupac/ember-aupac-typeahead#11]
Hello,

First thank you very much for this library.
It does mostly what I need and save me a fair amount of work.

The only thing I was able to configure, is a way to allow free inputs.

This is definitively possible on the original typeahead library, but I could not find a way to avoid having the control being emptied when the user does not make a selection.
I found a workaround by adding the query text to the top of the result, but it does not quite feel right.

Is it possible to allow free input ?
If yes, how ? Would it be possible include the explanation in the documentation ?
If no, could this be implemented ?

Thank you.
ymh

PS: to explore, I have tried to use the setValue property, but coud not really find how. When examining your code I am not sure that this property is really usable from "outside". If I am wrong, would it be possible to have a code example for this ? (something like reproducing the same functionality than the default value but adding a log of the argument, for example). thx.

**Comment by jackmatt2** [comment]
Are you using `aupac-typeahead` or `aupac-ember-data-typeahead`?  Can you supply an example of a free input in typeahead?  I had a look at their [examples](https://twitter.github.io/typeahead.js/examples/) page but can't see anything about free inputs.

**Comment by jackmatt2** [comment]
Ah, I think I see what you mean now.  I might be able to add a `freeInput=true` option, but this would only be available for `aupac-typeahead` not `aupac-ember-data-typeahead`.

**Comment by jackmatt2** [comment]
ember-aupac-typeahead@2.0.4

pass new option `allowFreeInput=true`

**Comment by ymph** [comment]
Hello,
Thanks for the reactivity !

I upgraded and i works as expected.
Thank you again.

ymph
