### ISSUE TITLE
Action is fired when user clicks off input if allowFreeInput=true

### ISSUE THREAD

**Issue by scottwernervt** [aupac/ember-aupac-typeahead#21]
The typeahead action is being fired when `allowFreeInput=true` and user clicks off the input. I expect the action to fire if the user performs the following:
- Return key
- Mouse select
- Mobile touch

[ember-twiddle](https://ember-twiddle.com/8bb2a2c2448f1cbee941b0bc2af23daf?openFiles=templates.application.hbs%2C)

**appplication.js**

``` javascript
import Ember from 'ember';

const skills = ['Python', 'Javascript', 'Django']

export default Ember.Controller.extend({
  skill: null,
  skillSource: function(query, syncResults, asyncResults) {
    const regex = new RegExp('.*' + query + '.*', 'i');
    const results = skills.filter((item, index, enumerable) => {
      return regex.test(item);
    })
    syncResults(results);
  },
  actions: {
    selectSkill(skill) {
      console.log('selectSkill action fired');
      this.set('skill', skill);
    }
  }
});
```

**application.hbs**

``` handlebars
{{aupac-typeahead 
    action=(action "selectSkill") 
    source=skillSource 
    allowFreeInput=true
}}
<br/>    
<b>Selected</b>: {{skill}}
{{outlet}}
```

**Comment by jackmatt2** [comment]
Thanks, I will look into fixing this for the next release.

**Comment by jackmatt2** [comment]
Actually this is the correct behaviour.  allowFreeInput allows the user to type whatever they like into the input field or choose something from the autocomplete list.
