### ISSUE TITLE
Is there a way to set the tabindex ?

### ISSUE THREAD

**Issue by frunjik** [aupac/ember-aupac-typeahead#25]
How to set the tabindex ?

I tried (quickly) by adding an attribute binding for tabindex,
but that does not seem to work ...

Is there some other way to set the tabindex (from a template) ?

**Comment by jackmatt2** [comment]
Not that I know of right now. I can add it as a feature though.

**Comment by frunjik** [comment]
How would you go about that ?

For now I have a workaround by setting the element.tabIndex in some
component.didInsertElement, but i would like a better (cleaner) solution...

2016-09-27 23:17 GMT+02:00 Jack Matthews notifications@github.com:

> Not that I know of right now. I can add it as a feature though.
>
