### ISSUE TITLE
Doesn't display all found suggestions

### ISSUE THREAD

**Issue by tevch** [aupac/ember-aupac-typeahead#32]
dropzoneSource: Ember.computed(function () {
        const _this = this;
        return function (query, syncResults, asyncResults) {
          var dropzones = _this.get('activeRegisteredDropzones');
          
          var results = dropzones.filter(function(record){
            var dz_name = record.get('dz_name');
            return dz_name.toLowerCase().indexOf(query.toLowerCase()) >= 0;
          });

          console.log('from names: found '+results.length+' dropzones');

          if(results.length<=0) {
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode( { "address": query }, function(geoResults, status) {
              if (status == google.maps.GeocoderStatus.OK && geoResults.length > 0) {
                var geoResult = geoResults[0];
                var geoResultLatLng = {latitude: geoResult.geometry.location.lat(), longitude: geoResult.geometry.location.lng()};

                results = dropzones.filter(function(record){
                  var dzLatLng = {latitude: record.get('lat'), longitude: record.get('lon')};
                  var inside = geolib.isPointInCircle(geoResultLatLng, dzLatLng, 200000);
                  return inside;
                });
                console.log('from radius: found '+results.length+' dropzones');
              }
              asyncResults(results);
            });
          } else {
            syncResults(results);
          }
        };
      })

What happens is this:

searching for phrase "Gardiner" produces 3 results, and displays 3
searching for phrase "new york" produces 13 results, but displays ONLY 2

both searches trigger async geo search

what could be the problem?
how would i even start figuring out why some results are not displayed?

Thanks

**Comment by jackmatt2** [comment]
Could it be to do with the case "new york" vs "New York"?

**Comment by jackmatt2** [comment]
As a test, can I suggest hard coding the returned results instead of actually hitting the API.  That might reveal something on interest.

**Comment by jackmatt2** [comment]
Since you are using the async function your might need `async=true` on the component also.  This is part of the typeahead API. I wouldn't mix `syncResults` and `asyncResults ` either.  Use one or the other.

**Comment by panthony** [comment]
Since you are using async results you may encounter the following bug:

https://github.com/twitter/typeahead.js/pull/1212

**Comment by jackmatt2** [comment]
This sounds like it would be resolved by #46
