### ISSUE TITLE
Support Ember 2.10 / Glimmer 2

### ISSUE THREAD

**Issue by pjcarly** [aupac/ember-aupac-typeahead#34]
Hi,

First of all, I love the addon, it's really great. 
However, I tried to upgrade my application to Ember 2.10  with Glimmer 2, and i'm running into an issue that I can trace back to this addon.

I don't really understand that much about it to be honest, but if you need any extra information or I can lend a hand, let me know.

`ember.debug.js:16911 Error: Cannot instantiate a component without a renderer. Please ensure that you are creating <Ember.Component:ember5407> with a proper container/registry.`

**Comment by jackmatt2** [comment]
I think this has been fixed by #31

**Comment by jackmatt2** [comment]
ember-aupac-typeahead@2.1.0

**Comment by pjcarly** [comment]
Cheers, confirmed to be fixed with 2.1, I upgraded before, but for some reason only to 2.0.8

**Comment by jackmatt2** [comment]
Can you confirm that it is working at ember@2.10.0?  I just release 2.1.0 yesterday, that is why you were only able to upgrade to 2.0.8 before.  It is not working for my locally at this version.

**Comment by pjcarly** [comment]
I'm not having any problems with 2.10, working perfectly so far. if there's anything I can do to help you figure it out. Let me know

**Comment by jackmatt2** [comment]
This is fixed now in the 2.1.1 release I will put out today.  I suspect you are using ember-data models which is working fine.  The problem was with models that were strings.
