### ISSUE TITLE
Not working in Ember 2.11

### ISSUE THREAD

**Issue by kennethlarsen** [aupac/ember-aupac-typeahead#38]
I just upgraded to Ember 2.11 and aupac-typeahead is not working anymore. 

It seems to be related to the creation and rendering of components: http://emberjs.com/deprecations/v2.x/#toc_code-rendertoelement-code

**Comment by jackmatt2** [comment]
What version of ember-aupac-typeahead are you using?  I just upgraded my local copy to ember@2.11.0 and it is working.  Can you first try upgrading to ember-aupac-typeahead@2.1.2.

**Comment by kennethlarsen** [comment]
My bad - for some reason typeahead wasn't updated. Thanks!
