### ISSUE TITLE
Dependency on typeahead.js

### ISSUE THREAD

**Issue by snewcomer** [aupac/ember-aupac-typeahead#45]
Any thoughts on trying to integrate https://github.com/corejavascript/typeahead.js/ instead of what looks like the no longer maintained version of it?

**Comment by theseyi** [comment]
I agree with this, there are several issues with the no longer maintained version of Twitter's typeahead, including https://github.com/twitter/typeahead.js/issues/1232 which has several PR's that are still open including the issue itself.

**Comment by jackmatt2** [comment]
Yep, can't see any issues with this. Will accept a pull request updating
the dependency assuming all tests pass.

**Comment by theseyi** [comment]
@jackmatt2 will do in a minute

**Comment by jackmatt2** [comment]
Resolved via #46
