### ISSUE TITLE
Uses Bower instead of NPM for some dependencies

### ISSUE THREAD

**Issue by robertbenjamin** [aupac/ember-aupac-typeahead#50]
As of Ember 2.12, Ember [no longer installs Bower](https://emberjs.com/blog/2017/03/19/ember-2-12-released.html) to manage dependencies since it's a bit redundant when it NPM performs the same task.

It'd be nice to move the 4 dependencies in bower.json (pretender, faker, bootstrap, and corejs-typeahead) to package.json and reference them from their location in `node_modules` instead of the bower directory.

This is something I'm hoping to tackle this weekend but I just wanted to make an issue first to see if you guys had any thoughts!

**Comment by jackmatt2** [comment]
Sure, this seams reasonable. pretender & faker come from ember-cli-mirage so you might want to try updating that too. You will also need to ensure users can still use their own version on typeahead if they so choose.

**Comment by jackmatt2** [comment]
Currently working on this.

**Comment by jackmatt2** [comment]
FIXED ember-aupac-typeahead@3.0.0
