### ISSUE TITLE
Not possible to use two on the same page

### ISSUE THREAD

**Issue by robertbenjamin** [aupac/ember-aupac-typeahead#51]
It seems that the `selection` property is fixed and set globally for each page's scope. This means that if you have two typeahead autocomplete components on the same page, they will override each other's selection property, making it impossible to use two at the same time.

I think it would make the most sense for this component to require you to pass the name of the selection property to change where the selected value is stored, thus allowing you to use as many as necessary.

**Comment by jackmatt2** [comment]
This should not be the case unless you are binding to the exact same selection property.
