### ISSUE TITLE
Start using a CHANGELOG.md file

### ISSUE THREAD

**Issue by acorncom** [aupac/ember-aupac-typeahead#6]
I'm finding the use of a `CHANGELOG.md` is a huge help when using a number of different add-ons and periodically upgrading them.  Here's an example of a change log that's saved me a ton of headaches over time: https://github.com/simplabs/ember-simple-auth/blob/master/CHANGELOG.md

Would it be possible to start using one for this add-on as well?

**Comment by jackmatt2** [comment]
Yep, I was going to do this but forgot.
