### ISSUE TITLE
Breaks with Ember 3.1: Cannot read property 'fullName' of undefined 

### ISSUE THREAD

**Issue by luketheobscure** [aupac/ember-aupac-typeahead#65]
Just upgraded a project to Ember 3.1 and this package throws an error when trying to instantiate - `TypeError: Cannot read property 'fullName' of undefined`.

It looks like the error stems from [this code](https://github.com/aupac/ember-aupac-typeahead/blob/ca3b89ed82171cddbfb9440f899f456cdf33dd2d/addon/components/aupac-typeahead.js#L134).

I found a similar issue [here](https://github.com/emberjs/ember.js/issues/16483), and there's a suggested workaround there.

**Comment by pjcarly** [comment]
+1
